### ISSUE TITLE
netgroup support missing

### ISSUE THREAD

**Issue by Rocco83** [tehmaze/getent#5]
Hi,

netgroup support is missing.
This is not very trivial because contents is not set in netgroups.

<getent.libc.LP_NetgroupStruct object at 0x7f20563ff9e0>
<class 'getent.libc.LP_NetgroupStruct'>
<built-in method __ctypes_from_outparam__ of LP_NetgroupStruct object at 0x7f20563ff9e0>
<method-wrapper '__delattr__' of LP_NetgroupStruct object at 0x7f20563ff9e0>
<method-wrapper '__delitem__' of LP_NetgroupStruct object at 0x7f20563ff9e0>
{}
None
<built-in method __format__ of LP_NetgroupStruct object at 0x7f20563ff9e0>
<method-wrapper '__getattribute__' of LP_NetgroupStruct object at 0x7f20563ff9e0>
<method-wrapper '__getitem__' of LP_NetgroupStruct object at 0x7f20563ff9e0>
<method-wrapper '__getslice__' of LP_NetgroupStruct object at 0x7f20563ff9e0>
<method-wrapper '__hash__' of LP_NetgroupStruct object at 0x7f20563ff9e0>
<method-wrapper '__init__' of LP_NetgroupStruct object at 0x7f20563ff9e0>
'getent.libc'
<built-in method __new__ of _ctypes.PyCPointerType object at 0x7f2054ba8e40>
<method-wrapper '__nonzero__' of LP_NetgroupStruct object at 0x7f20563ff9e0>
<built-in method __reduce__ of LP_NetgroupStruct object at 0x7f20563ff9e0>
<built-in method __reduce_ex__ of LP_NetgroupStruct object at 0x7f20563ff9e0>
<method-wrapper '__repr__' of LP_NetgroupStruct object at 0x7f20563ff9e0>
<method-wrapper '__setattr__' of LP_NetgroupStruct object at 0x7f20563ff9e0>
<method-wrapper '__setitem__' of LP_NetgroupStruct object at 0x7f20563ff9e0>
<built-in method __setstate__ of LP_NetgroupStruct object at 0x7f20563ff9e0>
<built-in method __sizeof__ of LP_NetgroupStruct object at 0x7f20563ff9e0>
<method-wrapper '__str__' of LP_NetgroupStruct object at 0x7f20563ff9e0>
<built-in method __subclasshook__ of _ctypes.PyCPointerType object at 0x106b340>

**Comment by tehmaze** [comment]
Fixed in merging pr#6
